apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "tfa.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels }}
    {{ toYaml .Values.deployment.labels | indent 4}}
    {{- end }}
  {{- if .Values.deployment.annotations }}
  annotations:
    {{ toYaml .Values.deployment.annotations | indent 4}}
  {{- end }}
  name: {{ include "tfa.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "tfa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tfa.labels" . | nindent 8 }}
        {{- if .Values.deployment.podLabels }}
        {{ toYaml .Values.deployment.podLabels | indent 8}}
        {{- end }}
      {{- if .Values.deployment.podAnnotations }}
      annotations:
        {{ toYaml .Values.deployment.podAnnotations | indent 8}}
      {{- end }}
    spec:
      containers:
        - name: {{ include "tfa.name" . }}
          image: "{{.Values.global.image.registry}}/{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{.Values.config.port}}
              protocol: TCP
          env:
            - name: CONFIG
              value: /conf/config.ini
            {{- if .Values.deployment.extraEnv}}
              {{- with .Values.deployment.extraEnv }}
                {{- toYaml . | nindent 10 }}
              {{- end }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "tfa.name" . }}
            {{- with .Values.deployment.extraEnvFrom }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /conf
              name: tfa-config
          livenessProbe:
            tcpSocket:
              port: 4181
            initialDelaySeconds: 20
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 2

      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tfa-config
          configMap:
            name: {{ include "tfa.name" . }}
            items:
              - key: "config.ini"
                path: "config.ini"

  strategy:
    type: {{.Values.deployment.updateStrategy}}
