{{ if .Values.middleware.enabled }}
apiVersion: {{ .Values.traefik.apiVersion }}
kind: Middleware
metadata:
  name: {{ include "tfa.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
spec:
  forwardAuth:
    address: "http://{{ include "tfa.name" .}}.{{.Values.namespace | default .Release.Namespace}}.svc.cluster.local:{{.Values.service.port}}"
    authResponseHeaders:
      {{- range .Values.middleware.authResponseHeaders}}
      - {{ . }}
      {{- end}}
    trustForwardHeader: {{.Values.middleware.trustForwardHeader}}
{{end}}
