{{- if not .Values.secret.external }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ tpl .Values.secret.name $ }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "tfa.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.secret}}
  SECRET: {{ printf "%s" .Values.config.secret | b64enc }}
  {{- end}}
  {{- if .Values.config.provider.google}}
  {{- if .Values.config.provider.google.clientSecret}}
  PROVIDERS_GOOGLE_CLIENT_SECRET: {{ printf "%s" .Values.config.provider.google.clientSecret | b64enc }}
  {{- end}}
  {{- end}}
  {{- if .Values.config.provider.oidc}}
  {{- if .Values.config.provider.oidc.clientSecret}}
  PROVIDERS_OIDC_CLIENT_SECRET: {{ printf "%s" .Values.config.provider.oidc.clientSecret | b64enc }}
  {{- end}}
  {{- end}}
  {{- if .Values.config.provider.generic}}
  {{- if .Values.config.provider.generic.clientSecret}}
  PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET: {{ printf "%s" .Values.config.provider.generic.clientSecret | b64enc }}
  {{- end}}
  {{- end}}
{{- end}}
