kind: Service
apiVersion: v1
metadata:
  name: {{ include "tfa.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "tfa.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
      {{ toYaml .Values.service.labels | indent 4}}
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "tfa.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.port }}
      protocol: TCP
