{{- if .Values.echo.enabled}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "tfa.name" .}}-echo
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
spec:
  entryPoints:
    {{ .Values.echo.service.ingress.entryPoints }}
  routes:
    {{- range .Values.echo.service.ingress.routes }}
    - match: {{ tpl .match $ }}
      kind: Rule
        {{- if .middlewares }}
      middlewares:
        {{- range .middlewares }}
        - name: {{ tpl (.name | toString) $ }}
        {{- end }}
      {{- end }}
      services:
        {{- range .services }}
        - name: {{ tpl (.name | toString) $ }}
          port: {{ .port }}
            {{- if .scheme }}
          scheme: {{ .scheme }}
            {{- end }}
        {{- end }}
    {{- end }}
{{- end}}
