name: Release

on:
  release:
    types: [ created ]

env:
  KO_OPTS: --tags ${{ github.event.release.tag_name }} --tags latest

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:

          go-version: 1.20.x

      - name: Check out code
        uses: actions/checkout@v3


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Ko
        run: go install github.com/google/ko@latest

      - name: Install Vendor
        run: go mod vendor

      - name: Build image
        run: make docker

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
